### ISSUE TITLE
Ruby 3.1.0 not supported due to depricated module

### ISSUE THREAD

**Issue by craig** [jglovier/resume-template#165]
```
[resume-template ]$ bundle exec jekyll serve
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `require': cannot load such file -- rexml/parsers/baseparser (LoadError)
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `<top (required)>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/html.rb:10:in `require'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/html.rb:10:in `<top (required)>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/paragraph.rb:14:in `require'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/paragraph.rb:14:in `<top (required)>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:345:in `require'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:345:in `<class:Kramdown>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:60:in `<module:Parser>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:19:in `<module:Kramdown>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:17:in `<top (required)>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll/converters/smartypants.rb:3:in `require'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll/converters/smartypants.rb:3:in `<top (required)>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:13:in `require'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:13:in `block in require_all'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:12:in `each'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:12:in `require_all'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:194:in `<top (required)>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/exe/jekyll:8:in `require'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/exe/jekyll:8:in `<top (required)>'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/bin/jekyll:25:in `load'
        from /home/craig/VCS/resume-template/_vendor/bundle/ruby/3.1.0/bin/jekyll:25:in `<main>'

```

**Comment by VenkattaPidikiti** [comment]
I am getting same error

**Comment by creme332** [comment]
See the solution which involves using a newer bundler: https://github.com/jglovier/resume-template/issues/168#issuecomment-2798726922
