### ISSUE TITLE
Build with Jekyll

### ISSUE THREAD

**Issue by VenkattaPidikiti** [jglovier/resume-template#168]
Hello ,
Good day !. 
I am using resume template from Github. while commiting changes to files then am getting below error.
Here is error details and please guide me to resolve the issue
Run bundle exec jekyll build --baseurl "/resume"
  bundle exec jekyll build --baseurl "/resume"
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_PAGES: true
    JEKYLL_ENV: production
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
bundler: failed to load command: jekyll (/home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/bin/jekyll)
LoadError: cannot load such file -- rexml/parsers/baseparser
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `require'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `<top (required)>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/html.rb:10:in `require'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/html.rb:10:in `<top (required)>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/paragraph.rb:14:in `require'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/paragraph.rb:14:in `<top (required)>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:345:in `require'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:345:in `<class:Kramdown>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:60:in `<module:Parser>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:19:in `<module:Kramdown>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:17:in `<top (required)>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll/converters/smartypants.rb:3:in `require'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll/converters/smartypants.rb:3:in `<top (required)>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:13:in `require'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:13:in `block in require_all'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:1[2](https://github.com/VenkattaPidikiti/resume/actions/runs/9238386279/job/25416382900#step:5:2):in `each'
  /home/runner/work/resume/resume/vendor/bundle/ruby/[3](https://github.com/VenkattaPidikiti/resume/actions/runs/9238386279/job/25416382900#step:5:3).1.0/gems/jekyll-3.8.7/lib/jekyll.rb:12:in `require_all'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/lib/jekyll.rb:19[4](https://github.com/VenkattaPidikiti/resume/actions/runs/9238386279/job/25416382900#step:5:4):in `<top (required)>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/exe/jekyll:8:in `require'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/gems/jekyll-3.8.7/exe/jekyll:8:in `<top (required)>'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/bin/jekyll:2[5](https://github.com/VenkattaPidikiti/resume/actions/runs/9238386279/job/25416382900#step:5:5):in `load'
  /home/runner/work/resume/resume/vendor/bundle/ruby/3.1.0/bin/jekyll:25:in `<top (required)>'
Error: Process completed with exit code 1.

Thank you for support,
Venkata Ravikumar Pidikiti

**Comment by creme332** [comment]
This issue is caused by the 2.1.4 bundler specified in the `Gemfile.lock`. It can be fixed by deleting the current `Gemfile.lock` and using a newer bundler, e.g. `bundle _2.5.11_ install`.

**Comment by eostb** [comment]
用Ai帮你解决问题吧
