### ISSUE TITLE
Could not find i18n-0.8.0

### ISSUE THREAD

**Issue by DudeWhoCode** [jglovier/resume-template#31]
When I clone the theme and run `jekyll build` or `jekyll serve` It throws following error, But it never happens for other themes.

```
/Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find i18n-0.8.0 in any of the sources (Bundler::GemNotFound)
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `map!'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `materialize'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler/definition.rb:159:in `specs'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler/definition.rb:218:in `specs_for'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler/definition.rb:207:in `requested_specs'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:109:in `block in definition_method'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:21:in `setup'
        from /Library/Ruby/Gems/2.0.0/gems/bundler-1.15.1/lib/bundler.rb:101:in `setup'
        from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by jglovier** [comment]
@DudeWhoCode sorry for the delayed response! 

I'm unable to reproduce this. Can you pull the latest from `gh-pages` branch and try again? I just pushed an update to the gemfile which may address the problem for you.
